# -*- coding: utf-8 -*-
"""استعداد یابی ورزش ووشو با هوش مصنوعی.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abc123xyz

# 🥋 سیستم استعدادیابی ورزش ووشو با هوش مصنوعی

## نصب و راه‌اندازی کتابخانه‌های مورد نیاز
"""

!pip install opencv-python mediapipe scikit-learn pandas numpy matplotlib seaborn streamlit pillow joblib
!pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
!pip install streamlit -q

import warnings
warnings.filterwarnings('ignore')

"""## 1. بخش اول: ارزیابی مبتنی بر داده‌های متنی"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import joblib
import json
import os

class TextBasedWushuTalentAssessment:
    """
    کلاس ارزیابی استعداد ووشو بر اساس داده‌های متنی
    """
    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.label_encoder = LabelEncoder()
        self.feature_names = [
            'age', 'weight', 'height', 'flexibility', 'power', 
            'speed', 'endurance', 'balance', 'coordination',
            'reaction_time', 'mental_focus', 'competitive_spirit'
        ]
        
        # وزن ویژگی‌ها برای محاسبه امتیاز
        self.feature_weights = {
            'age': 0.10,
            'weight': 0.05,
            'height': 0.05,
            'flexibility': 0.15,
            'power': 0.12,
            'speed': 0.10,
            'endurance': 0.10,
            'balance': 0.08,
            'coordination': 0.08,
            'reaction_time': 0.07,
            'mental_focus': 0.05,
            'competitive_spirit': 0.05
        }
        
        # سبک‌های ووشو
        self.styles = {
            0: 'تالو (فرم) - مبتدی',
            1: 'تالو (فرم) - پیشرفته',
            2: 'ساندا (مبارزه) - سبک‌وزن',
            3: 'ساندا (مبارزه) - سنگین‌وزن',
            4: 'ترکیبی - مناسب هر دو سبک'
        }
        
    def create_sample_dataset(self, n_samples=1000):
        """
        ایجاد دیتاست نمونه برای آموزش مدل
        """
        np.random.seed(42)
        
        data = []
        for i in range(n_samples):
            # تولید داده‌های تصادفی
            age = np.random.randint(8, 35)
            weight = np.random.uniform(30, 100)
            height = np.random.uniform(130, 195)
            
            # ویژگی‌های فیزیکی (مقیاس 1-10)
            flexibility = np.random.randint(1, 11)
            power = np.random.randint(1, 11)
            speed = np.random.randint(1, 11)
            endurance = np.random.randint(1, 11)
            balance = np.random.randint(1, 11)
            coordination = np.random.randint(1, 11)
            reaction_time = np.random.randint(1, 11)
            
            # ویژگی‌های ذهنی
            mental_focus = np.random.randint(1, 11)
            competitive_spirit = np.random.randint(1, 11)
            
            # محاسبه امتیاز کلی
            features = np.array([
                age, weight, height, flexibility, power, speed,
                endurance, balance, coordination, reaction_time,
                mental_focus, competitive_spirit
            ])
            
            # نرمال‌سازی سن برای امتیازدهی
            age_score = 10 - abs(age - 15) / 10  # اوج استعداد در 15 سالگی
            
            # تعیین سبک بر اساس ویژگی‌ها
            if flexibility > 7 and balance > 6:
                if age < 18 and coordination > 7:
                    style = 1  # تالو پیشرفته
                else:
                    style = 0  # تالو مبتدی
            elif power > 7 and speed > 6:
                if weight < 70:
                    style = 2  # ساندا سبک‌وزن
                else:
                    style = 3  # ساندا سنگین‌وزن
            else:
                style = 4  # ترکیبی
            
            data.append([
                age, weight, height, flexibility, power, speed,
                endurance, balance, coordination, reaction_time,
                mental_focus, competitive_spirit, style
            ])
        
        columns = self.feature_names + ['recommended_style']
        df = pd.DataFrame(data, columns=columns)
        return df
    
    def train_model(self, df=None):
        """
        آموزش مدل طبقه‌بندی
        """
        if df is None:
            df = self.create_sample_dataset()
        
        X = df[self.feature_names]
        y = df['recommended_style']
        
        # استانداردسازی
        X_scaled = self.scaler.fit_transform(X)
        
        # آموزش مدل
        self.model = RandomForestClassifier(
            n_estimators=100,
            max_depth=10,
            random_state=42
        )
        self.model.fit(X_scaled, y)
        
        print("✅ مدل با موفقیت آموزش داده شد!")
        print(f"دقت مدل: {self.model.score(X_scaled, y):.2%}")
        return self.model
    
    def assess_talent(self, user_data):
        """
        ارزیابی استعداد کاربر بر اساس داده‌های ورودی
        """
        if self.model is None:
            self.train_model()
        
        # تبدیل داده‌های ورودی به آرایه
        features = np.array([[
            user_data['age'],
            user_data['weight'],
            user_data['height'],
            user_data['flexibility'],
            user_data['power'],
            user_data['speed'],
            user_data['endurance'],
            user_data['balance'],
            user_data['coordination'],
            user_data['reaction_time'],
            user_data['mental_focus'],
            user_data['competitive_spirit']
        ]])
        
        # استانداردسازی
        features_scaled = self.scaler.transform(features)
        
        # پیش‌بینی سبک
        style_pred = self.model.predict(features_scaled)[0]
        style_prob = self.model.predict_proba(features_scaled)[0]
        
        # محاسبه امتیاز کلی
        total_score = 0
        for i, feature in enumerate(self.feature_names):
            if feature in ['age', 'weight', 'height']:
                # نرمال‌سازی ویژگی‌های عددی
                if feature == 'age':
                    norm_value = 10 - abs(user_data[feature] - 15) / 10
                elif feature == 'weight':
                    norm_value = user_data[feature] / 100
                elif feature == 'height':
                    norm_value = user_data[feature] / 200
                total_score += norm_value * self.feature_weights[feature] * 10
            else:
                total_score += user_data[feature] * self.feature_weights[feature]
        
        # تولید توصیه‌ها
        recommendations = self._generate_recommendations(user_data, style_pred, total_score)
        
        return {
            'total_score': round(total_score, 2),
            'recommended_style': self.styles[style_pred],
            'style_confidence': round(max(style_prob) * 100, 2),
            'style_probabilities': {self.styles[i]: round(prob * 100, 2) for i, prob in enumerate(style_prob)},
            'strengths': recommendations['strengths'],
            'weaknesses': recommendations['weaknesses'],
            'training_recommendations': recommendations['training'],
            'detailed_analysis': self._detailed_analysis(user_data)
        }
    
    def _generate_recommendations(self, user_data, style_pred, total_score):
        """
        تولید توصیه‌های شخصی‌سازی شده
        """
        strengths = []
        weaknesses = []
        training_recs = []
        
        # تحلیل نقاط قوت
        if user_data['flexibility'] >= 7:
            strengths.append("انعطاف‌پذیری عالی")
            training_recs.append("تمرینات حفظ انعطاف‌پذیری")
        else:
            weaknesses.append("انعطاف‌پذیری نیاز به بهبود دارد")
            training_recs.append("تمرینات کششی روزانه")
        
        if user_data['balance'] >= 7:
            strengths.append("تعادل خوب")
            training_recs.append("تمرینات تعادل پیشرفته")
        else:
            weaknesses.append("تعادل نیاز به تقویت دارد")
            training_recs.append("تمرینات تعادل پایه")
        
        if user_data['power'] >= 7:
            strengths.append("قدرت بدنی بالا")
        else:
            weaknesses.append("قدرت بدنی نیاز به افزایش دارد")
            training_recs.append("تمرینات قدرتی")
        
        # توصیه‌های بر اساس سبک
        if style_pred in [0, 1]:  # تالو
            training_recs.extend([
                "تمرین فرم‌های پایه ووشو",
                "کار بر روی دقت حرکات",
                "تمرینات نمایشی"
            ])
        elif style_pred in [2, 3]:  # ساندا
            training_recs.extend([
                "تمرینات مبارزه با شریک",
                "کار بر روی تکنیک‌های ضربه و دفاع",
                "تمرینات استقامتی"
            ])
        else:  # ترکیبی
            training_recs.extend([
                "تمرینات متنوع از هر دو سبک",
                "توسعه مهارت‌های پایه",
                "کار بر روی نقاط ضعف"
            ])
        
        return {
            'strengths': strengths,
            'weaknesses': weaknesses,
            'training': list(set(training_recs))
        }
    
    def _detailed_analysis(self, user_data):
        """
        تحلیل جزئی ویژگی‌ها
        """
        analysis = {}
        
        # تحلیل سن
        age = user_data['age']
        if age < 12:
            analysis['age'] = "سن پایین - زمان عالی برای شروع آموزش پایه"
        elif 12 <= age <= 18:
            analysis['age'] = "سن ایده‌آل برای توسعه مهارت‌های تخصصی"
        elif 19 <= age <= 25:
            analysis['age'] = "سن مناسب برای رقابت‌های حرفه‌ای"
        else:
            analysis['age'] = "سن مناسب برای تمرینات تفریحی و سلامتی"
        
        # تحلیل ویژگی‌های فیزیکی
        for feature in ['flexibility', 'power', 'speed', 'endurance', 'balance']:
            value = user_data[feature]
            if value >= 8:
                analysis[feature] = "عالی"
            elif value >= 6:
                analysis[feature] = "خوب"
            elif value >= 4:
                analysis[feature] = "متوسط"
            else:
                analysis[feature] = "نیاز به بهبود"
        
        return analysis
    
    def save_model(self, path='wushu_text_model.joblib'):
        """
        ذخیره مدل آموزش دیده
        """
        if self.model:
            joblib.dump({
                'model': self.model,
                'scaler': self.scaler,
                'feature_names': self.feature_names,
                'styles': self.styles
            }, path)
            print(f"✅ مدل در {path} ذخیره شد.")
    
    def load_model(self, path='wushu_text_model.joblib'):
        """
        بارگذاری مدل از فایل
        """
        if os.path.exists(path):
            data = joblib.load(path)
            self.model = data['model']
            self.scaler = data['scaler']
            self.feature_names = data['feature_names']
            self.styles = data['styles']
            print("✅ مدل با موفقیت بارگذاری شد.")
        else:
            print("⚠️ فایل مدل یافت نشد. مدل جدید آموزش داده می‌شود.")
            self.train_model()

"""### تست بخش متنی"""

# ایجاد نمونه از کلاس ارزیابی
text_assessor = TextBasedWushuTalentAssessment()

# آموزش مدل
print("در حال آموزش مدل ارزیابی متنی...")
text_assessor.train_model()

# تست با داده‌های نمونه کاربر
test_user = {
    'age': 16,
    'weight': 65,
    'height': 175,
    'flexibility': 8,
    'power': 7,
    'speed': 8,
    'endurance': 6,
    'balance': 9,
    'coordination': 8,
    'reaction_time': 7,
    'mental_focus': 8,
    'competitive_spirit': 9
}

print("\n🔍 در حال ارزیابی استعداد ورزشکار...")
result = text_assessor.assess_talent(test_user)

print(f"\n🎯 نتایج ارزیابی:")
print(f"امتیاز کلی: {result['total_score']}/100")
print(f"سبک توصیه شده: {result['recommended_style']}")
print(f"قطعیت پیش‌بینی: {result['style_confidence']}%")

print(f"\n✅ نقاط قوت:")
for strength in result['strengths']:
    print(f"  - {strength}")

print(f"\n📝 نیازهای بهبود:")
for weakness in result['weaknesses']:
    print(f"  - {weakness}")

print(f"\n💪 توصیه‌های تمرینی:")
for rec in result['training_recommendations'][:5]:
    print(f"  - {rec}")

"""## 2. بخش دوم: تحلیل Pose Detection"""

import cv2
import mediapipe as mp
import numpy as np
from IPython.display import Image, display
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import math

class WushuPoseAnalyzer:
    """
    کلاس تحلیل فرم بدن و حرکات ووشو با استفاده از MediaPipe
    """
    def __init__(self):
        self.mp_pose = mp.solutions.pose
        self.pose = self.mp_pose.Pose(
            static_image_mode=False,
            model_complexity=1,
            smooth_landmarks=True,
            min_detection_confidence=0.5,
            min_tracking_confidence=0.5
        )
        self.mp_drawing = mp.solutions.drawing_utils
        
        # تعریف نقاط کلیدی برای ووشو
        self.key_points = {
            'nose': 0,
            'left_shoulder': 11,
            'right_shoulder': 12,
            'left_elbow': 13,
            'right_elbow': 14,
            'left_wrist': 15,
            'right_wrist': 16,
            'left_hip': 23,
            'right_hip': 24,
            'left_knee': 25,
            'right_knee': 26,
            'left_ankle': 27,
            'right_ankle': 28
        }
        
    def calculate_angle(self, a, b, c):
        """
        محاسبه زاویه بین سه نقطه
        """
        a = np.array(a)
        b = np.array(b)
        c = np.array(c)
        
        radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
        angle = np.abs(radians*180.0/np.pi)
        
        if angle > 180.0:
            angle = 360 - angle
            
        return angle
    
    def analyze_image(self, image_path):
        """
        تحلیل فرم بدن از یک تصویر
        """
        # خواندن تصویر
        image = cv2.imread(image_path)
        if image is None:
            print(f"⚠️ تصویر {image_path} یافت نشد!")
            return None
        
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = self.pose.process(image_rgb)
        
        if not results.pose_landmarks:
            print("❌ هیچ فرم بدنی تشخیص داده نشد!")
            return None
        
        # رسم نقاط کلیدی روی تصویر
        annotated_image = image.copy()
        self.mp_drawing.draw_landmarks(
            annotated_image,
            results.pose_landmarks,
            self.mp_pose.POSE_CONNECTIONS,
            landmark_drawing_spec=self.mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=2),
            connection_drawing_spec=self.mp_drawing.DrawingSpec(color=(255, 0, 0), thickness=2)
        )
        
        # استخراج نقاط کلیدی
        landmarks = results.pose_landmarks.landmark
        h, w, _ = image.shape
        
        key_positions = {}
        for name, idx in self.key_points.items():
            landmark = landmarks[idx]
            key_positions[name] = (int(landmark.x * w), int(landmark.y * h))
        
        # تحلیل فرم
        analysis = self._analyze_posture(key_positions)
        
        # نمایش تصویر
        plt.figure(figsize=(10, 10))
        plt.imshow(cv2.cvtColor(annotated_image, cv2.COLOR_BGR2RGB))
        plt.title("تحلیل فرم بدن - ووشو")
        plt.axis('off')
        plt.show()
        
        return analysis
    
    def analyze_video(self, video_path, output_path='analyzed_video.mp4'):
        """
        تحلیل فرم بدن از ویدئو
        """
        cap = cv2.VideoCapture(video_path)
        
        if not cap.isOpened():
            print(f"⚠️ ویدئو {video_path} یافت نشد!")
            return None
        
        # مشخصات ویدئو
        fps = int(cap.get(cv2.CAP_PROP_FPS))
        width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        
        # تعریف کدک و خروجی
        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
        out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))
        
        frame_analyses = []
        frame_count = 0
        
        print("🎬 در حال تحلیل ویدئو...")
        
        while cap.isOpened():
            ret, frame = cap.read()
            
            if not ret:
                break
            
            frame_count += 1
            if frame_count % 30 == 0:
                print(f"📊 تحلیل فریم {frame_count}...")
            
            # پردازش فریم
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            results = self.pose.process(frame_rgb)
            
            annotated_frame = frame.copy()
            
            if results.pose_landmarks:
                # رسم نقاط کلیدی
                self.mp_drawing.draw_landmarks(
                    annotated_frame,
                    results.pose_landmarks,
                    self.mp_pose.POSE_CONNECTIONS
                )
                
                # استخراج و تحلیل نقاط
                landmarks = results.pose_landmarks.landmark
                key_positions = {}
                
                for name, idx in self.key_points.items():
                    landmark = landmarks[idx]
                    key_positions[name] = (int(landmark.x * width), int(landmark.y * height))
                
                # تحلیل فرم این فریم
                frame_analysis = self._analyze_posture(key_positions)
                frame_analyses.append(frame_analysis)
                
                # نمایش اطلاعات روی ویدئو
                cv2.putText(annotated_frame, f"Balance: {frame_analysis['balance_score']:.1f}", 
                           (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
                cv2.putText(annotated_frame, f"Flexibility: {frame_analysis['flexibility_score']:.1f}", 
                           (50, 100), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 255), 2)
                cv2.putText(annotated_frame, f"Style: {frame_analysis['recommended_style']}", 
                           (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2)
            
            out.write(annotated_frame)
        
        cap.release()
        out.release()
        print(f"✅ ویدئو تحلیل شده در {output_path} ذخیره شد.")
        
        # تحلیل کلی ویدئو
        if frame_analyses:
            video_analysis = self._aggregate_video_analysis(frame_analyses)
            return video_analysis
        
        return None
    
    def _analyze_posture(self, key_positions):
        """
        تحلیل فرم بدن بر اساس نقاط کلیدی
        """
        analysis = {}
        
        # محاسبه زوایا
        try:
            # زاویه زانو (برای تحلیل تعادل)
            if all(k in key_positions for k in ['left_hip', 'left_knee', 'left_ankle']):
                left_knee_angle = self.calculate_angle(
                    key_positions['left_hip'],
                    key_positions['left_knee'],
                    key_positions['left_ankle']
                )
                analysis['left_knee_angle'] = left_knee_angle
            else:
                left_knee_angle = 170  # مقدار پیش‌فرض
            
            if all(k in key_positions for k in ['right_hip', 'right_knee', 'right_ankle']):
                right_knee_angle = self.calculate_angle(
                    key_positions['right_hip'],
                    key_positions['right_knee'],
                    key_positions['right_ankle']
                )
                analysis['right_knee_angle'] = right_knee_angle
            else:
                right_knee_angle = 170
            
            # زاویه آرنج (برای تحلیل قدرت)
            if all(k in key_positions for k in ['left_shoulder', 'left_elbow', 'left_wrist']):
                left_elbow_angle = self.calculate_angle(
                    key_positions['left_shoulder'],
                    key_positions['left_elbow'],
                    key_positions['left_wrist']
                )
                analysis['left_elbow_angle'] = left_elbow_angle
            else:
                left_elbow_angle = 160
            
            # تحلیل تعادل
            balance_score = 100 - abs(left_knee_angle - right_knee_angle) * 2
            balance_score = max(0, min(100, balance_score))
            analysis['balance_score'] = balance_score
            
            # تحلیل انعطاف‌پذیری
            avg_knee_angle = (left_knee_angle + right_knee_angle) / 2
            flexibility_score = max(0, min(100, (180 - avg_knee_angle) * 2))
            analysis['flexibility_score'] = flexibility_score
            
            # تحلیل قدرت
            power_score = min(100, left_elbow_angle * 0.5)
            analysis['power_score'] = power_score
            
            # تحلیل هماهنگی
            shoulder_diff = abs(key_positions.get('left_shoulder', (0, 0))[1] - 
                              key_positions.get('right_shoulder', (0, 0))[1])
            hip_diff = abs(key_positions.get('left_hip', (0, 0))[1] - 
                          key_positions.get('right_hip', (0, 0))[1])
            
            coordination_score = 100 - (shoulder_diff + hip_diff)
            coordination_score = max(0, min(100, coordination_score))
            analysis['coordination_score'] = coordination_score
            
            # تشخیص سبک مناسب
            if flexibility_score > 70 and balance_score > 75:
                if coordination_score > 80:
                    recommended_style = "تالو (فرم) - پیشرفته"
                    style_points = 4
                else:
                    recommended_style = "تالو (فرم) - مبتدی"
                    style_points = 3
            elif power_score > 65 and balance_score > 70:
                # تشخیص وزن بر اساس نسبت قد و وزن (تخمینی)
                shoulder_width = abs(key_positions.get('left_shoulder', (0, 0))[0] - 
                                   key_positions.get('right_shoulder', (0, 0))[0])
                if shoulder_width > 100:  # تخمینی
                    recommended_style = "ساندا (مبارزه) - سنگین‌وزن"
                    style_points = 2
                else:
                    recommended_style = "ساندا (مبارزه) - سبک‌وزن"
                    style_points = 1
            else:
                recommended_style = "ترکیبی - نیاز به تمرین بیشتر"
                style_points = 0
            
            analysis['recommended_style'] = recommended_style
            analysis['style_points'] = style_points
            
            # امتیاز کلی
            overall_score = (
                balance_score * 0.3 +
                flexibility_score * 0.25 +
                power_score * 0.2 +
                coordination_score * 0.25
            )
            analysis['overall_score'] = overall_score
            
            # نقاط قوت و ضعف
            strengths = []
            weaknesses = []
            
            if balance_score > 80:
                strengths.append("تعادل عالی")
            elif balance_score < 60:
                weaknesses.append("تعادل نیاز به بهبود دارد")
            
            if flexibility_score > 75:
                strengths.append("انعطاف‌پذیری خوب")
            elif flexibility_score < 50:
                weaknesses.append("انعطاف‌پذیری محدود")
            
            if power_score > 70:
                strengths.append("قدرت بدنی مناسب")
            
            analysis['strengths'] = strengths
            analysis['weaknesses'] = weaknesses
            
        except Exception as e:
            print(f"خطا در تحلیل فرم: {e}")
            return None
        
        return analysis
    
    def _aggregate_video_analysis(self, frame_analyses):
        """
        تجمیع تحلیل‌های فریم‌های ویدئو
        """
        if not frame_analyses:
            return None
        
        # میانگین گرفتن از امتیازها
        avg_scores = {
            'balance_score': np.mean([f.get('balance_score', 0) for f in frame_analyses]),
            'flexibility_score': np.mean([f.get('flexibility_score', 0) for f in frame_analyses]),
            'power_score': np.mean([f.get('power_score', 0) for f in frame_analyses]),
            'coordination_score': np.mean([f.get('coordination_score', 0) for f in frame_analyses]),
            'overall_score': np.mean([f.get('overall_score', 0) for f in frame_analyses])
        }
        
        # تشخیص سبک غالب
        style_counts = {}
        for f in frame_analyses:
            style = f.get('recommended_style', '')
            if style:
                style_counts[style] = style_counts.get(style, 0) + 1
        
        if style_counts:
            dominant_style = max(style_counts, key=style_counts.get)
        else:
            dominant_style = "تعیین نشد"
        
        # جمع‌بندی نقاط قوت و ضعف
        all_strengths = []
        all_weaknesses = []
        
        for f in frame_analyses:
            all_strengths.extend(f.get('strengths', []))
            all_weaknesses.extend(f.get('weaknesses', []))
        
        common_strengths = list(set([s for s in all_strengths 
                                   if all_strengths.count(s) > len(frame_analyses) * 0.3]))
        common_weaknesses = list(set([w for w in all_weaknesses 
                                    if all_weaknesses.count(w) > len(frame_analyses) * 0.3]))
        
        return {
            'average_scores': avg_scores,
            'dominant_style': dominant_style,
            'common_strengths': common_strengths,
            'common_weaknesses': common_weaknesses,
            'frame_count': len(frame_analyses),
            'consistency': np.std([f.get('overall_score', 0) for f in frame_analyses])
        }
    
    def generate_pose_report(self, image_path=None, video_path=None):
        """
        تولید گزارش کامل از تحلیل فرم
        """
        analysis = None
        
        if image_path:
            print(f"📷 تحلیل تصویر: {image_path}")
            analysis = self.analyze_image(image_path)
        elif video_path:
            print(f"🎥 تحلیل ویدئو: {video_path}")
            analysis = self.analyze_video(video_path)
        else:
            print("⚠️ لطفا مسیر تصویر یا ویدئو را مشخص کنید.")
            return
        
        if analysis:
            print("\n📊 گزارش تحلیل فرم بدنی:")
            print("=" * 50)
            
            if 'average_scores' in analysis:  # ویدئو
                scores = analysis['average_scores']
                print(f"\n🎯 امتیازهای میانگین:")
                for key, value in scores.items():
                    print(f"  {key}: {value:.1f}/100")
                
                print(f"\n🥋 سبک غالب: {analysis['dominant_style']}")
                print(f"📈 تعداد فریم‌های تحلیل شده: {analysis['frame_count']}")
                print(f"🎭 ثبات عملکرد: {analysis['consistency']:.2f}")
                
            else:  # تصویر
                print(f"\n🎯 امتیازها:")
                for key, value in analysis.items():
                    if 'score' in key or 'angle' in key:
                        if 'score' in key:
                            print(f"  {key}: {value:.1f}/100")
                        else:
                            print(f"  {key}: {value:.1f}°")
                
                print(f"\n🥋 سبک توصیه شده: {analysis.get('recommended_style', 'تعیین نشد')}")
            
            if 'strengths' in analysis and analysis['strengths']:
                print(f"\n✅ نقاط قوت تشخیص داده شده:")
                for strength in analysis['strengths']:
                    print(f"  - {strength}")
            
            if 'weaknesses' in analysis and analysis['weaknesses']:
                print(f"\n📝 نقاط نیازمند بهبود:")
                for weakness in analysis['weaknesses']:
                    print(f"  - {weakness}")
            
            print("\n💡 توصیه‌ها:")
            if analysis.get('flexibility_score', 0) < 60:
                print("  - تمرینات کششی روزانه را افزایش دهید")
            if analysis.get('balance_score', 0) < 65:
                print("  - روی تمرینات تعادل مانند ایستادن روی یک پا کار کنید")
            if analysis.get('power_score', 0) < 50:
                print("  - تمرینات قدرتی پایه‌ای اضافه کنید")
            
            print("=" * 50)
            
        return analysis

"""### تست Pose Detection"""

# ایجاد نمونه تحلیل‌گر
pose_analyzer = WushuPoseAnalyzer()

print("🔄 تحلیل‌گر Pose Detection آماده است.")

# تست با یک تصویر نمونه (اگر تصویری در Colab آپلود کرده‌اید)
# برای تست، ابتدا یک تصویر آپلود کنید:
from google.colab import files

print("📤 لطفا یک تصویر برای تحلیل آپلود کنید...")
uploaded = files.upload()

if uploaded:
    image_name = list(uploaded.keys())[0]
    print(f"✅ تصویر {image_name} آپلود شد.")
    
    # تحلیل تصویر
    pose_analysis = pose_analyzer.generate_pose_report(image_path=image_name)
else:
    print("⚠️ هیچ تصویری آپلود نشد. ادامه با داده‌های نمونه...")
    
    # ایجاد یک تصویر نمونه با OpenCV
    sample_image = np.zeros((400, 400, 3), dtype=np.uint8)
    cv2.putText(sample_image, "تصویر نمونه ووشو", (50, 200), 
                cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2)
    
    cv2.imwrite('sample_wushu.jpg', sample_image)
    print("📸 تصویر نمونه ایجاد شد.")

"""## 3. بخش سوم: سیستم پیش‌بینی مسابقات"""

import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib
from datetime import datetime

class WushuMatchPredictor:
    """
    سیستم پیش‌بینی نتایج مسابقات ووشو
    """
    def __init__(self):
        self.model = None
        self.scaler = StandardScaler()
        self.features = [
            'age', 'weight', 'height', 'experience_years',
            'win_rate', 'avg_match_duration', 'stamina_index',
            'technical_skill', 'mental_toughness', 'recent_form',
            'opponent_age', 'opponent_weight', 'opponent_height',
            'opponent_experience', 'opponent_win_rate',
            'weight_diff', 'height_diff', 'experience_diff'
        ]
        
    def create_match_dataset(self, n_matches=500):
        """
        ایجاد دیتاست مسابقات برای آموزش مدل
        """
        np.random.seed(42)
        
        matches = []
        
        for i in range(n_matches):
            # ایجاد داده‌های تصادفی برای دو ورزشکار
            athlete1 = self._create_random_athlete()
            athlete2 = self._create_random_athlete()
            
            # محاسبه تفاوت‌ها
            weight_diff = athlete1['weight'] - athlete2['weight']
            height_diff = athlete1['height'] - athlete2['height']
            experience_diff = athlete1['experience_years'] - athlete2['experience_years']
            
            # ویژگی‌های ترکیبی
            features = [
                athlete1['age'], athlete1['weight'], athlete1['height'],
                athlete1['experience_years'], athlete1['win_rate'],
                athlete1['avg_match_duration'], athlete1['stamina_index'],
                athlete1['technical_skill'], athlete1['mental_toughness'],
                athlete1['recent_form'],
                athlete2['age'], athlete2['weight'], athlete2['height'],
                athlete2['experience_years'], athlete2['win_rate'],
                weight_diff, height_diff, experience_diff
            ]
            
            # تعیین برنده بر اساس شبیه‌سازی
            winner = self._simulate_match(athlete1, athlete2)
            
            matches.append(features + [winner])
        
        columns = self.features + ['winner']
        df = pd.DataFrame(matches, columns=columns)
        return df
    
    def _create_random_athlete(self):
        """
        ایجاد داده‌های تصادفی برای یک ورزشکار
        """
        age = np.random.randint(16, 35)
        weight = np.random.uniform(55, 95)
        height = np.random.uniform(160, 190)
        experience_years = np.random.randint(1, 15)
